language: objective-c
osx_image: xcode8
env:
  - LC_CTYPE=en_US.UTF-8
git:
  submodules: false
before_install:
  - git submodule update --init --recursive
script:
  - set -o pipefail && xcodebuild test -scheme CSV-OSX
notifications:
  email: false
